services:
#    store.example:
#        class: StoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app.set_trajectory:
        class: StoreBundle\invoice\set_trajectory